### ISSUE TITLE
Uncaught (in promise) TypeError: (0 , i.default) is not a function

### ISSUE THREAD

**Issue by adityarai** [nasa8x/rss-to-json#56]
Installed new empty project in react v^18.2.0

Page is blank. Getting error in console.

`index.js:1 Uncaught (in promise) TypeError: (0 , i.default) is not a function
    at t.default (index.js:1:1)
    at App.js:7:1
    at App (App.js:10:1)
    at renderWithHooks (react-dom.development.js:16305:1)
    at mountIndeterminateComponent (react-dom.development.js:20145:1)
    at beginWork (react-dom.development.js:21587:1)
    at beginWork$1 (react-dom.development.js:27426:1)
    at performUnitOfWork (react-dom.development.js:26557:1)
    at workLoopSync (react-dom.development.js:26466:1)
    at renderRootSync (react-dom.development.js:26434:1)
t.default @ index.js:1
(anonymous) @ App.js:7
App @ App.js:10
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20145
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
await in performWorkUntilDeadline (async)
App @ App.js:10
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20145
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533`

Package.json
`{
  "name": "test-rss-to-json",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-scripts": "5.0.1",
    "rss-to-json": "^2.1.1",
    "web-vitals": "^2.1.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
`

**Comment by QasimRRizvi** [comment]
Same issue
```
index.js:1 Uncaught (in promise) TypeError: (0 , i.default) is not a function
    at t.default (index.js:1:1)
    at getJob (jobs.ts:19:1)
    at handleGetJobs (App.tsx:93:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:1)
    at invokeGuardedCallback (react-dom.development.js:4277:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4291:1)
    at executeDispatch (react-dom.development.js:9041:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:9073:1)
    at processDispatchQueue (react-dom.development.js:9086:1)
```

**Comment by mcaquet** [comment]
Same issue:

```
index.js:17 Uncaught (in promise) TypeError: (0 , i.default) is not a function
    at t.default (index.js:17:1)
```

**Comment by ttrreevvoorr** [comment]
This is happening for me when including rss-to-json in some React projects. I am not sure what exactly is causing it, as I can run rss-to-json in _other_ React projects, and always on its own in a `test.js` file, using the same code, calling it in the same way.
